language: ruby
rvm:
  #- 1.9.3
  #- 2.0.0
  #- ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-2.1.1
gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
notifications:
  email: false
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rspec spec/
